module DomainDefinition

  LDAP_HOST = ENV['LDAP_HOST']
  LDAP_PORT = ENV['LDAP_PORT']
  LDAP_CONNECTSTRING = ENV['LDAP_CONNECTSTRING']
  USER_GROUP_STUDENT = ENV['LDAP_STUDENT_GROUP']
  USER_GROUP_INSTRUCTOR = ENV['LDAP_INSTRUCTOR_GROUP']
  ORGANISATION_DOMAIN  = ENV['ORGANISATION_DOMAIN']

end